### PR TITLE
German website translations

### PR DESCRIPTION
**Pull request by AlexanderHeidrich**
Hey. I just finished the first translations-draft for the website.
There are some labels where I don't know the context, as the labels are not part of the repository/the *.tsx-files does not exist.

Does someone know the german translation for Dimension Hub? 
* I know that some other campaigns name it "Dimensionsnarbe" or something like this, as Dunwich mentions something similar like "Riss in Raum und Zeit". 

What is the context of the event labels, or who is meant by "You have to "
* Is it plural? _You (all) have to ..._
* Is it singular? _Hey Player XY, you have to_
* I currently have focused on the singular case but I can imagine most of the labels adressing all players of the group, right?

### CODE REVIEW

**Comment by zzorba** [comment]
I believe the german rule guide will mention Dimension Hub during setup: https://asmodee-resources.azureedge.net/media/germanyprod/Produkte/Arkham%20Horror:%20LCG/AH_LCG_Krieg%20der%20Aeu%C3%9Feren%20Goetter.pdf

As for the You instructions, they are targeting a user of the app/website generally.  

"You must set a handle before you can invite friends." -- an error message that might show up if you try to add a friend without a handle.

"Your group has been eliminated." -- the leader of the table in this case, who is using the website.
"Your group" -- label on your groups name in the overview page for an event.

I think singular is probably correct here?

**Comment by AlexanderHeidrich** [comment]
I've just recrawled my Arkham Hhorror chest and found "The Blob" in German.
So I will go over the translations again :)

**Comment by zzorba** [comment]
Awesome thank you @AlexanderHeidrich.  Let me know when this is ready and I'll merge it and get arkhamcards.com deployed.

**Comment by AlexanderHeidrich** [comment]
**Note:** There is no announcement for defeating _Silenus_ in _assets/i18n-web/frontend/de.po:448_

**Comment by AlexanderHeidrich** [comment]
I guess I'm done so far.
I just optimized the translations a bit after reviewing all of them again.

**Pull request merged**
